[__config__]
oldver = "/config/old_ver.json"
newver = "/config/new_ver.json"

[deej]
source = "github"
github = "omriharel/deej"
use_latest_release = "true"

[gestures]
source = "gitlab"
gitlab = "cunidev/gestures"
use_max_tag = "true"

[git-secret]
source = "github"
github = "sobolevn/git-secret"
use_latest_release = "true"

[google-cloud-sdk-gke-gcloud-auth-plugin]
source = "apt"
pkg = "google-cloud-cli-gke-gcloud-auth-plugin"
mirror = "https://packages.cloud.google.com/apt"
suite = "cloud-sdk"
repo = "main"
arch = "amd64"
# https://packages.cloud.google.com/apt/dists/cloud-sdk/main/binary-amd64/Packages

[kiibohd-configurator]
source = "github"
github = "kiibohd/configurator"
use_latest_release = "true"

[pcloud-drive]
source = "regex"
url = "https://api.pcloud.com/getlastversion?os=ELECTRON"
regex = "\"version\": \"([\\d\\.]+)\","

[ttf-adobe-source-code-pro]
source = "github"
github = "adobe-fonts/source-code-pro"
use_latest_release = "true"

[ttf-adobe-source-sans]
source = "github"
github = "adobe-fonts/source-sans"
use_latest_release = "true"

[ttf-adobe-source-serif]
source = "github"
github = "adobe-fonts/source-serif"
use_latest_release = "true"

[wireguard-vanity-keygen]
source = "github"
github = "axllent/wireguard-vanity-keygen"
use_latest_release = "true"
